First PR for Policy Manifest reconcillation effort (mostly so Franco can comment).
giantswarm/kyverno-policy-operator pull request #98
Opened 2024-04-15 21:07 UTC by Strigix

This PR is created after a first basic working version of the policy manifest reconciliation was created.
Mostly so that Franco can comment on improvements.

2024-04-15 23:10 UTC, fhielpos requested changes

2024-04-15 23:10 UTC, fhielpos commented on internal/controller/utils.go
> +
We can delete this I believe

2024-04-15 23:10 UTC, fhielpos commented on internal/controller/utils.go
> +				Names:      target.Names,
We need to check if the `target.Names` include `"*"` or append it.

2024-04-15 23:10 UTC, fhielpos commented on internal/controller/policymanifest_controller.go
> +// - https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.17.0/pkg/reconcile
This can go away

2024-04-15 23:10 UTC, fhielpos commented on internal/controller/policymanifest_controller.go
> +	kpe.Labels["app.kubernetes.io/managed-by"] = "kyverno-policy-operator"
This is exactly the same for all the controllers, we should add a new helper function in utils that actually handles the setup of the base labels.

2024-04-15 23:10 UTC, fhielpos commented on internal/controller/policymanifest_controller.go
> +	kpe.Spec.Background = &r.Background
This may also be possible to do in a helper function since we do this for all the controllers too.

2024-04-15 23:10 UTC, fhielpos commented on internal/controller/policymanifest_controller.go
> +	policyMap[polman.Name] = kyvernoPolicy
Since we reconcile ClusterPolicies, using a cache would be better than going to the api server every time

2024-04-15 23:10 UTC, fhielpos commented on internal/controller/policymanifest_controller.go
> +	kpe := kyvernov2beta1.PolicyException{}
Personal preference, but I like more explicit names like `kyvernoPolicyException` or just `policyException`. But that's just me.

2024-04-15 23:10 UTC, fhielpos commented on internal/controller/policymanifest_controller.go
> +	kpe.Namespace = r.DestinationNamespace
Need to ensure that `r.DestinationNamespace` is not empty.

2024-04-15 23:11 UTC, fhielpos commented
Also CI is failing so you may want to do a `go mod tidy`.

2024-04-15 23:11 UTC, fhielpos commented on helm/kyverno-policy-operator/crd/policymanifests.yaml
This file is not needed in this PR.

2024-05-02 12:00 UTC, fhielpos commented on internal/controller/clusterpolicy_controller.go
> +	}
I would always override the cache because the ClusterPolicy could have changed.

2024-05-02 12:02 UTC, fhielpos commented on internal/controller/clusterpolicy_controller.go
> +	if err != nil {
I don't feel this is right because you are conditioning the "Get", and the controller should always fetch the ClusterPolicy in case it has changed.

2024-05-02 12:03 UTC, fhielpos commented on internal/controller/clusterpolicy_controller.go
> +	// If it's not in the cache, query the policy
Same as the first comment, we shouldn't condition the Get of the ClusterPolicy, that should always happen, and I would personally prefer if that happens in the Reconcile method directly.

2024-05-08 13:09 UTC, fhielpos commented on internal/controller/policymanifest_controller.go
> +	if kyvernoPolicy, ok = r.PolicyCache[polman.Name]; !ok {
You don't need to declare the variables if you assign them in the `if` condition.

```
	if kyvernoPolicy, ok := r.PolicyCache[polman.Name]; !ok {
```

2024-05-08 13:13 UTC, fhielpos commented on internal/controller/clusterpolicy_controller.go
>  		// Check if the ClusterPolicy was deleted
Looks good. Here, if the policy was deleted, I would also check and remove it from the map.

2024-05-08 13:13 UTC, fhielpos commented
Since now this looks way better, would you mind running nancy-fixer so we can see if CI is good?

2024-05-15 18:00 UTC, fhielpos approved these changes
I renamed the PR. This looks good to me, good job!

I would suggest just merging this massive PR and then keep working on different PRs for tests, metrics and those.

2024-05-15 20:06 UTC, stone-z approved these changes
Ok with me to continue in followups. I think there's a logic issue in the clusterpolicy controller but we can get this beast merged and continue in smaller bites

2024-05-16 10:13 UTC, Strigix commented
A lot of your questions are valid, but are about parts that mostly Franco worked on before.
I'll discuss these with him today!

2024-05-16 10:53 UTC, fhielpos commented on internal/controller/clusterpolicy_controller.go
> +								r.ExceptionList[clusterPolicy.Name] = clusterPolicy
I thought this had been removed but I may have missed it

2024-05-16 10:53 UTC, fhielpos commented on internal/controller/policymanifest_controller_test.go
> +			// TODO(user): Add more specific assertions depending on your controller's reconciliation logic.
Yeah, I prefer to have it in another PR because this was already massive

2024-05-16 10:55 UTC, fhielpos commented on internal/controller/policymanifest_controller.go
> +	kyvernoPolicyException.Labels["policy.giantswarm.io/policy"] = polman.ObjectMeta.Labels["policy.giantswarm.io/policy"]
I agree, I would prefer the policy-api approach

2024-05-16 11:52 UTC, fhielpos commented on internal/controller/policymanifest_controller.go
> +	policyMap := make(map[string]kyvernov1.ClusterPolicy)
Yeah, this is just coming from the first implementations I did. There are a couple things to refactor.

2024-05-22 12:15 UTC, merged

2024-05-23 14:55 UTC, Strigix commented on internal/controller/policymanifest_controller.go
> +	}
I think I've correctly changed it in a later PR, but I've got some questions for when you get back regarding this :)